Exception on /gm/gmtools/profile/11951050037377 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 412, in gm_tools_controls_profile
    return render_template('controls_profile.html', profile=profile)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/templates/controls_profile.html", line 3, in top-level template code
    {% extends 'layout.html' %}
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/templates/layout.html", line 8, in top-level template code
    {% set authority_list = [('none','none'),('gm_1','gm_1'),('gm_2','gm_2'),('gm_3','gm_3')] %}
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/templates/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/templates/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/templates/base.html", line 6, in block "html"
    {%- block head %}
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/templates/base.html", line 14, in block "head"
    {%- block styles %}
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/templates/controls_profile.html", line 6, in block "styles"
    <link href="{{ url_for('.static/bootstrap-switch/css/bootstrap3', filename='bootstrap-switch.css') }}"
  File "/usr/local/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'blue_print.static/bootstrap-switch/css/bootstrap3' with values ['filename']. Did you mean 'blue_print.static' instead?
Exception on /gm/test/mysql [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 824, in test_mysql
    mysql_info = query_player_from_mysql_test('gogogo')
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 970, in query_player_from_mysql_test
    mysql_info['userDesc'] = p.userDesc
AttributeError: 'BaseQuery' object has no attribute 'userDesc'
Exception on /gm/test/mysql [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 824, in test_mysql
    mysql_info = query_player_from_mysql_test('gogogo')
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 970, in query_player_from_mysql_test
    mysql_info['userDesc'] = p.userDesc
AttributeError: 'BaseQuery' object has no attribute 'userDesc'
Exception on /gm/test/mysql [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 824, in test_mysql
    mysql_info = query_player_from_mysql_test('gogogo')
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 970, in query_player_from_mysql_test
    mysql_info['userDesc'] = p.userDesc
AttributeError: 'BaseQuery' object has no attribute 'userDesc'
Exception on /gm/test/mysql [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 824, in test_mysql
    mysql_info = query_player_from_mysql_test('gogogo')
  File "/Users/zouyang/PycharmProjects/GMTools_Flask/route.py", line 972, in query_player_from_mysql_test
    mysql_info['suspensionExpiredDate'] = p.suspensionExpiredDate
AttributeError: 'PlayerInfo' object has no attribute 'suspensionExpiredDate'
Exception on /gm/test/mysql [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
Exception on /gm/test/mysql [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
